name: Live Environment | Build and Deploy

on:
  # Allow us to trigger a build manually - allows you to release to live when you
  # are comfortable..
  # @see https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:

jobs:
  buildAndDeploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # @see https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
      # @see https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-azure-pipelines-to-github-actions#migrating-conditionals-and-expression-syntax
      - name: Check Branch
        if: ${{ !startsWith(github.ref, 'refs/heads/release/') }}
        run: exit 1

      - name: Read .nvmrc
        run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
        id: nvm

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: echo "replace this line with your extra tests!"

      - name: Deploy Artifact
        run: echo "deploying to live!"

